// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OcazAPI.Services.CarAPI.CarDbContexts;

#nullable disable

namespace OcazAPI.Services.CarAPI.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OcazAPI.Services.CarAPI.Models.Cars", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("CarCarburant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("CarImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CarKm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CarTrans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            CarCarburant = "Essence",
                            CarDesc = "4cylindre 2l avec 200hp 320Nm",
                            CarImage = new byte[0],
                            CarKm = "100 000km",
                            CarModel = "2012",
                            CarName = "Bwm Serie3",
                            CarTrans = "Automatique"
                        },
                        new
                        {
                            CarId = 2,
                            CarCarburant = "Diesel",
                            CarDesc = "4cylindre 1.2l avec 120hp 300Nm",
                            CarImage = new byte[0],
                            CarKm = "120 000km",
                            CarModel = "2015",
                            CarName = "Toyota corolla",
                            CarTrans = "Manuel"
                        },
                        new
                        {
                            CarId = 3,
                            CarCarburant = "Diesel",
                            CarDesc = "4cylindre 1.6l avec 160hp 320Nm",
                            CarImage = new byte[0],
                            CarKm = "95 520km",
                            CarModel = "2016",
                            CarName = "Hyundai tucson",
                            CarTrans = "Manuel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
